# renew_before_expiry = 30 days
version = 3.0.1
archive_dir = /etc/letsencrypt/archive/am2design.ru
cert = /etc/letsencrypt/live/am2design.ru/cert.pem
privkey = /etc/letsencrypt/live/am2design.ru/privkey.pem
chain = /etc/letsencrypt/live/am2design.ru/chain.pem
fullchain = /etc/letsencrypt/live/am2design.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 55f423d3a4f331c313215bfdd6fddd51
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
am2design.ru = /var/www/certbot
